apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +optional Incoming connection details for the component (AKA endpoints).
  inbound:
    # +required Unique name for the endpoint. (This name will be used when generating the managed API)
    - name: portalservice
      # +required Numeric port value that gets exposed via the endpoint
      port: 8080
      # +required Type of traffic that the endpoint is accepting. For example: REST, GraphQL, etc.
      # Allowed values: REST, GraphQL, GRPC, TCP, UDP.
      type: REST
      # +optional Network level visibility of the endpoint. Defaults to Public
      # Accepted values: Project|Organization|Public.
      networkVisibility: Public
      # +optional Context (base path) of the API that gets exposed via the endpoint.
      # This is mandatory if the endpoint type is set to REST or GraphQL.
      context: /
      # +optional The path to the schema definition file. Defaults to wildcard route if not specified.
      # This is only applicable to REST endpoint types.
      # The path should be relative to the Docker context.
      schemaFilePath: openapi.yaml

  outbound:
    serviceReferences:
    - name: choreo:///ycrnet/api-analytics-service/oaiwjw/197f7/v1.0/ORGANIZATION
      connectionConfig: 01ef0107-3659-15e6-9d1a-7e2edc1009fa
      env:
      - from: ServiceURL
        to: ANALYTICS_API_URL
      - from: ConsumerKey
        to: CHOREO_OAUTH_CLIENT_ID
      - from: ConsumerSecret
        to: CHOREO_OAUTH_CLIENT_SECRET
      - from: TokenURL
        to: CHOREO_OAUTH_TOKEN_URL