openapi: 3.0.0
info:
  title: Report Generation API
  description: API for generating reports
  version: 1.0.0
paths:
  /api/v1/report/{granularity}/{apiName}/{startDate}/{startTime}/{endDate}/{endTime}:
    get:
      summary: Generate Report
      description: |
        Generate a report based on provided parameters.
      parameters:
        - name: granularity
          in: path
          description: Granularity of the data (hour or day)
          required: true
          schema:
            type: string
            enum: [hour, day]
        - name: apiName
          in: path
          description: Name of the API
          required: true
          schema:
            type: string
        - name: startDate
          in: path
          description: Start date of the data range (YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date
        - name: startTime
          in: path
          description: Start time of the data range (HH:mm:ss)
          required: true
          schema:
            type: string
            format: time
        - name: endDate
          in: path
          description: End date of the data range (YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date
        - name: endTime
          in: path
          description: End time of the data range (HH:mm:ss)
          required: true
          schema:
            type: string
            format: time
      responses:
        '200':
          description: Successful operation
          content:
            text/html:
              schema:
                type: string
                example: |
                  <!DOCTYPE html>
                  <html>
                    <head>
                      <title>Report</title>
                    </head>
                    <body>
                      <h1>Report Generated Successfully</h1>
                      <p>This is a sample report.</p>
                    </body>
                  </html>
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /api/v1/apis:
    get:
      summary: Get API List
      description: |
        Get the list of available APIs.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["TransactionAPI","CoverageAPI"]
        '500':
          description: Internal server error
